### ISSUE TITLE
ability to use a private key instead of ssh-agent

### ISSUE THREAD

**Issue by bartbouter** [CentreForDigitalHumanities/humitifier#43]
Implement a option that allows the use of a ssh private key with pssh.

The docs states this should be possible:
https://parallel-ssh.readthedocs.io/en/latest/ssh_parallel.html

pkey ([str](https://docs.python.org/2/library/functions.html#str) or bytes) – Private key file path to use. Path must be either absolute path or relative to user home directory like ~/<path>. Bytes type input is used as private key data for authentication.

**Comment by fliepeltje** [comment]
This seems straightforward, but even without docker it seems to not work. Some things to consider:

- When I run queries **without** the cratylus proxy specification, I cannot connect to the hosts (with my `donatas` user)
- If I specify the `allow_agent = false` flag to not use ssh the ssh agent, I get an error
- If I change no options and **only** add the `pkey` argument, I get an error too

Also, I get the feeling that through the ssh-agent this option is used:

- forward_ssh_agent ([bool](https://docs.python.org/2/library/functions.html#bool)) – (Optional) Turn on SSH agent forwarding - equivalent to ssh -A from the ssh command line utility. Defaults to False if not set. Currently unused meaning always off.

While the option can be set in pssh, it is not used functionally


### Variations

#### No proxy :x: 

```toml
[pssh]
user = "donatas"
timeout = 15
num_retries = 0
pool_size = 50
```

Output:

```bash
2023-11-22 09:09:30,392 - pssh.clients.base.single - ERROR - Error connecting to host 'gw-c-dh-people-and-parliament.im.hum.uu.nl:22' - retry 1/0
2023-11-22 09:09:30,393 - pssh.clients.base.parallel - ERROR - Failed to run on host gw-c-dh-people-and-parliament.im.hum.uu.nl - ("Error connecting to host '%s:%s' - %s - retry %s/%s", 'gw-c-dh-people-and-parliament.im.hum.uu.nl', 22, 'timed out', 1, 0)
``` 

#### Proxy, with (proxy_)pkey :x:

```toml
[pssh]
user = "donatas"
proxy_host = "cratylus.im.hum.uu.nl"
timeout = 15
num_retries = 0
pool_size = 50
pkey = "~/.ssh/id_rsa" # same for proxy_pkey)
```

```bash
2023-11-22 09:13:40,993 - pssh.clients.native.single - ERROR - Proxy authentication failed. Exception from tunnel client: ('Authentication error while connecting to %s:%s - %s - retries %s/%s', 'cratylus.im.hum.uu.nl', 22, KeyfileAuthFailedError(), 1, 0)
```

#### Proxy, no agent :x:

```toml
[pssh]
user = "donatas"
proxy_host = "cratylus.im.hum.uu.nl"
timeout = 15
num_retries = 0
pool_size = 50
allow_agent = false
```

```bash
2023-11-22 09:16:43,677 - pssh.clients.native.single - ERROR - Proxy authentication failed. Exception from tunnel client: ('Authentication error while connecting to %s:%s - %s - retries %s/%s', 'cratylus.im.hum.uu.nl', 22, AuthenticationError('No authentication methods succeeded'), 1, 0)
```

### Proxy, with ssh-agent :white_check_mark: 

```toml
[pssh]
user = "donatas"
proxy_host = "cratylus.im.hum.uu.nl"
timeout = 15
num_retries = 0
pool_size = 50
```

This works. 

### Questions

- is there something in ssh configuration that we can do to skip the cratylus proxy?

Also, note any options you specify under the `[pssh]` heading in the confguration, get directly passed into the client config. So you can modify and play around with them locally without having to mess around in the code.

**Comment by bartbouter** [comment]
after some localing testing with pssh i came up with the following working config:

```
from pssh.clients import ParallelSSHClient

hosts = ['server1.local.host',server2.local.host','server3.local.host']
client = ParallelSSHClient(
             hosts, user='ssh_username',
             port=22,
             pkey='~/.ssh/privatekey',
             allow_agent = False,
             proxy_host='sshproxyserver.local.host',
             proxy_user='ssh_username',
             proxy_port=22,
             proxy_pkey='~/.ssh/privatekey')

output = client.run_command('hostnamectl')
for host_output in output:
    for line in host_output.stdout:
        print(line)
    exit_code = host_output.exit_code
```

i think this should translate to the following configuration
```
[pssh]
user='ssh_username',
port=22,
pkey='~/.ssh/privatekey',
allow_agent = False,
proxy_host='sshproxyserver.local.host',
proxy_user='ssh_username',
proxy_port=22,
proxy_pkey='~/.ssh/privatekey')
timeout = 15
num_retries = 0
pool_size = 50
```

**Comment by fliepeltje** [comment]
I still get the same error with this configuration:

```bash
2023-11-22 16:46:22,122 - pssh.clients.native.single - ERROR - Proxy authentication failed. Exception from tunnel client: ('Authentication error while connecting to %s:%s - %s - retries %s/%s', 'cratylus.im.hum.uu.nl', 22, KeyfileAuthFailedError(), 1, 0)
```

**Comment by bartbouter** [comment]
I made some changes to the configuration of our humitifier server so it uses a privatekey for ssh auth. (no proxy needed on the server)

i changed the compose file on the server to:

```
version: '3'
services:
  web:
    image: ghcr.io/centrefordigitalhumanities/humitifier/humitifier:latest
    container_name: humitifier
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ${LOCAL_VOLUME}/app_config_compose.toml:/code/app_config.toml # Reference your configuration
      - ${LOCAL_VOLUME}/data:/data # Persistent volume for data
      - ${SSH_KEY}:/id_humitifier.key:ro
    restart: unless-stopped
```

the .env file looks like this:
```
# humitifier dir
LOCAL_VOLUME=/hum/humitifier
SSH_KEY=/root/.ssh/id_humitifier.key
HUMITIFIER_CONFIG=/code/app_config.toml
```

and app_config_compose.toml
```
db = "/data/facts.db"
inventory = "/data/inventory" # A directory with toml files with host configurations

[pssh] # any pssh configuration to access your servers
user = "humitifier"
timeout = 15
num_retries = 0
pool_size = 50
pkey = "/id_humitifier.key"
allow_agent = false

[tasks]
infra_update = "every 15 minutes"
```
